issue_prefix: btc-algo-trading

auto_sync:
  export_to_jsonl: true
  debounce_seconds: 5

auto_import:
  from_jsonl: true
  when_newer: true

daemon:
  auto_start: true

dolt:
  host: 10.10.20.138
  port: 3310
  database: beads_btc-algo-trading
  user: beads
  auto-commit: "on"
